#!/bin/bash

#######################################
# OpenShift start script for Sherlok  #
#######################################

cd ${OPENSHIFT_REPO_DIR}

# Fix Maven local repo
echo -e  "<settings>\n   <localRepository>$OPENSHIFT_DATA_DIR/.m2</localRepository>\n</settings>\n" > settings.xml

nohup mvn clean install exec:java \
-s settings.xml \
-Dmaven.test.skip=true \
-Dexec.mainClass="org.sherlok.SherlokServer" \
-Dexec.classpathScope=runtime \
-Dexec.args="-port ${OPENSHIFT_DIY_PORT} -address ${OPENSHIFT_DIY_IP}" \
> $OPENSHIFT_LOG_DIR/sherlok.log 2>&1 &
