<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <!-- Automatically generated by Sherlok at ${now} -->

  <groupId>org.sherlok</groupId>
  <artifactId>${pipelineName}</artifactId>
  <version>${pipelineVersion}</version>
  
  <dependencies>
    <!-- TODO workaround https://gist.githubusercontent.com/mantognini/2fbeec6fb86aa5290b89/raw/651009b68e72163141f24e982d0bf3bfaddce3ea/stack1 -->
    <dependency>
 	  <groupId>net.sf.trove4j</groupId>
 	  <artifactId>trove4j</artifactId>
 	  <version>2.0.2</version>
 	</dependency>
     
    <!-- current Sherlok version -->
    <dependency>
      <groupId>io.sherlok</groupId>
  	  <artifactId>sherlok_core</artifactId>
      <version>${sherlokVersion}</version>
    </dependency>
 
    <!-- pipeline dependencies -->  
  <#list deps as dep>
    <dependency>
      <groupId>${dep.groupId}</groupId>
      <artifactId>${dep.artifactId}</artifactId>
      <version>${dep.version}</version>
    </dependency>
  </#list>  
  </dependencies>

  <repositories>
  <#list repos as repo>
    <repository>
      <id>${repo.id}</id>
      <url>${repo.url}</url>
    </repository>
  </#list>
  </repositories>
    
  <!-- APPASSEMBLER to create one portable application -->
  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>appassembler-maven-plugin</artifactId>
        <version>1.10</version>
        <configuration>
          <!-- Add Java property for log to prevent ValidationException from 
            org.sherlok.UimaPipeline.initEngines(UimaPipeline.java:243) (line numbering 
            from 156718b0d11d5402e73de45406666a854fa09c5a) because MalletLogger might 
            write on syserr if this property is not set and resources/logging.properties 
            is not found. Note that log.properties doesn't have to exist to make this 
            work. -->
          <extraJvmArguments>-Djava.util.logging.config.file=log.properties -Dfile.encoding=UTF8 -Dsealed=${pipelineName}:${pipelineVersion}</extraJvmArguments>
          <programs>
            <program>
              <mainClass>org.sherlok.SherlokServer</mainClass>
              <id>sherlok_app</id>
            </program>
          </programs>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
